### ISSUE TITLE
Lua running out of memory?

### ISSUE THREAD

**Issue by ShortKidd** [kylecoburn/PokeBot#30]
Not sure if it's a script fault or BizHawk/something else fault. Might be a something else problem, because reloading BizHawk fixed it. Leaving this here just in case, though.

---------------------------

---------------------------
LuaInterface.LuaException: unprotected error in call to Lua API (not enough memory)

   at LuaInterface.Lua.PanicCallback(IntPtr luaState)

   at luaD_throw(lua_State* L, Int32 errcode)

   at luaM_realloc_(lua_State* L, Void* block, UInt32 osize, UInt32 nsize)

   at ?A0xe870b163.setarrayvector(lua_State* L, Table* t, Int32 size)

   at ?A0xe870b163.resize(lua_State* L, Table* t, Int32 nasize, Int32 nhsize)

   at ?A0xe870b163.rehash(lua_State* L, Table* t, lua_TValue* ek)

   at ?A0xe870b163.newkey(lua_State* L, Table* t, lua_TValue* key)

   at lua_rawseti(lua_State* L, Int32 idx, Int32 n)

   at luaL_ref(lua_State* L, Int32 t)

   at LuaInterface.ObjectTranslator.getFunction(IntPtr luaState, Int32 index)

   at LuaInterface.Lua.LoadFile(String fileName)

   at BizHawk.Client.EmuHawk.EmuLuaLibrary.SpawnCoroutine(String file)

   at BizHawk.Client.EmuHawk.LuaConsole.RunLuaScripts()
---------------------------
OK   
---------------------------

**Comment by mathiasbynens** [comment]
Seeing this as well. There seems to be a memory leak either in the bot code or in BizHawk itself. @kylecoburn How do you work around this for the Twitch stream? Do you quit and restart the bot every now and then in an automated way, or what?

**Comment by Marcin1503** [comment]
I had the same (or similar) after many runs.

**Comment by kylecoburn** [comment]
This is an issue with how BizHawk reloads the emulator when performing a reset, as best I can tell. The only workaround is to reopen the emulator.

**Comment by mathiasbynens** [comment]
Ref. #40.
